kind: pipeline
name: Kernel Compile
clone:
  disable: true
steps:
 - name: compile
   image: diazaji/python:kernel
   environment:
     TELEGRAM_TOKEN:
       from_secret: TELEGRAM_TOKEN
   commands:
      - cd /drone/src
      - wget https://github.com/Diaz1401/arrow_kernel_xiaomi_sm8250/archive/refs/heads/arrow-12.0.zip -O kernel.zip
      - unzip kernel.zip
      - wget -q https://raw.githubusercontent.com/Diaz1401/build-script/alioth/build-clang.sh
      - bash build-clang.sh 20220225
